# Generated by Django 6.0.3 on 2026-04-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auteur',
            old_name='nom',
            new_name='auteur',
        ),
    ]
