# Generated by Django 6.0.3 on 2026-04-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0003_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='ouvrages.etiquette'),
        ),
    ]
