# Generated by Django 6.0.3 on 2026-04-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0005_alter_article_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='est_publie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='nb_vues',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
