# Generated by Django 6.0.3 on 2026-04-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0012_alter_article_auteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auteur',
            old_name='auteur',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Auteur', to='ouvrages.auteur'),
        ),
    ]
