# Generated by Django 6.0.3 on 2026-04-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0015_alter_article_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Auteurs', to='ouvrages.auteur'),
        ),
    ]
