# Generated by Django 6.0.3 on 2026-04-14 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0020_alter_article_auteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auteur',
            old_name='nom',
            new_name='auteur',
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Auteurs', to='ouvrages.auteur'),
        ),
    ]
