# Generated by Django 6.0.3 on 2026-04-14 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0021_rename_nom_auteur_auteur_alter_article_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='tags',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to='ouvrages.etiquette'),
        ),
    ]
