# Generated by Django 6.0.3 on 2026-04-14 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0022_auteur_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='tags',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='ouvrages.etiquette'),
        ),
    ]
