# Generated by Django 6.0.3 on 2026-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0026_alter_auteur_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='tags',
            field=models.CharField(default=1, max_length=50, null=True),
        ),
    ]
