# Generated by Django 6.0.3 on 2026-04-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0027_alter_auteur_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auteur',
            name='tags',
        ),
    ]
