# Generated by Django 6.0.3 on 2026-04-14 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0028_remove_auteur_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='tags',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='etiquette', to='ouvrages.etiquette'),
        ),
    ]
