# Generated by Django 6.0.3 on 2026-04-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouvrages', '0030_alter_article_auteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auteur',
            new_name='ecrivains',
        ),
    ]
